### ISSUE TITLE
Theme broken from latest update.

### ISSUE THREAD

**Issue by Mikeysax** [smlombardi/oceanic-next-syntax#16]
![image](https://cloud.githubusercontent.com/assets/15805689/21949589/9de6ce24-d9c1-11e6-82aa-1ba1b7dee6ab.png)

Syntax highlighting was broken last update. (Atom 1.12.7)

![image](https://cloud.githubusercontent.com/assets/15805689/21949665/1a636b7e-d9c2-11e6-92e7-8c2d6df82468.png)

**Comment by DJTB** [comment]
Exactly the same for me: 
Ubuntu 16.04, Atom 1.12.7

Updated to Atom 1.13.0 and reinstalled oceanic -> fixed. 
(though the issue will still remain for 1.12.x users)

**Comment by gsklee** [comment]
I am afraid the expected behavior is that all Atom users who are not on v1.13.0 already should do the upgrade ASAP. Atom has explicitly stated inside the deprecation warning that auto-fixes for the shadow DOM selectors will be removed within a few more updates; see #12 for further details. Supporting old Atom versions will not be possible once that happens anyway.
